export const services = [
  {
    slug: "rhinoplasty",
    title: "Burun Estetiği (Rhinoplasty)",
    desc: "Yüzünüzle uyumlu, dengeli ve doğal bir burun profili oluşturma.",
    homeDesc: "Yüzle uyumlu, doğal ve dengeli bir burun profili.",
    src: "/assets/services/rhinoplasty.png",
    alt: "Burun estetiğini çağrıştıran görsel",
    featuredOnHome: true,
  },
  {
    slug: "breast-augmentation",
    title: "Meme Büyütme",
    desc: "Doğal hatları koruyarak daha dolgun ve dengeli bir görünüm.",
    homeDesc: "Doğal hatları koruyarak özgüveni artıran sonuçlar.",
    src: "/assets/services/breast-augmentation.png",
    alt: "Meme büyütmeyi çağrıştıran görsel",
    featuredOnHome: true,
  },
  {
    slug: "liposuction",
    title: "Liposuction",
    desc: "Vücut şekillendirme için belirli bölgelerdeki inatçı yağların azaltılması.",
    homeDesc: "Vücut şekillendirme ve inatçı yağların azaltılması.",
    src: "/assets/services/liposuction.png",
    alt: "Liposuction’ı çağrıştıran görsel",
    featuredOnHome: true,
  },
  {
    slug: "facelift",
    title: "Yüz Germe (Facelift)",
    desc: "Kırışıklık ve sarkmaları azaltarak daha genç ve dinç bir ifade.",
    homeDesc: "Daha genç, dinç ve taze bir yüz görünümü.",
    src: "/assets/services/facelift.png",
    alt: "Yüz germeyi çağrıştıran görsel",
    featuredOnHome: true,
  },
  {
    slug: "tummy-tuck",
    title: "Karın Germe (Tummy Tuck)",
    desc: "Fazla deri ve yağın azaltılması ile daha düz ve sıkı karın görünümü.",
    src: "/assets/services/tummy-tuck.png",
    alt: "Karın germeyi çağrıştıran illüstrasyon",
    featuredOnHome: false,
  },
  {
    slug: "blepharoplasty",
    title: "Göz Kapağı Estetiği",
    desc: "Üst ve alt göz kapaklarındaki fazla deri/yağın giderilmesi ile daha canlı bir bakış.",
    src: "/assets/services/eyelid-surgery.png",
    alt: "Göz kapağı estetiğini çağrıştıran görsel",
    featuredOnHome: false,
  },
];
